"use client";

import type { AppLanguage } from "@/shared/i18n/language";
import type { MaintenanceCopy } from "./types";

export function getMaintenanceCopy(language: AppLanguage): MaintenanceCopy {
  return language === "en"
    ? {
        title: "MAINTENANCE SCHEDULE",
        subtitle: "AI-Driven Preventative Maintenance & Work Orders",
        createTitle: "Create Schedule",
        editTitle: "Edit Schedule",
        target: "Target Equipment",
        targetCategory: "Equipment Category",
        task: "Task",
        schedule: "Schedule",
        scheduleDate: "Date",
        scheduleTime: "Time",
        notifyBefore: "Notification Timing",
        notifyBeforeHint: "Select when to send reminder notifications for preparation",
        notifyBeforeSameDay: "Same day",
        notifyBeforeOneDay: "1 day before",
        notifyBeforeOneWeek: "1 week before",
        notifyBeforeOneMonth: "1 month before",
        maintenanceCycle: "Maintenance Cycle",
        maintenanceCycleHint: "Auto-recurring cycle to avoid repeated manual entries",
        customDaysLabel: "Custom days",
        assigned: "Assignee",
        notify: "Email Reminder",
        notes: "Notes",
        submit: "Create Schedule",
        update: "Save Changes",
        edit: "Edit",
        delete: "Delete",
        cancelEdit: "Cancel Edit",
        sentAt: "Sent At",
        notSent: "Not sent yet",
        deleteConfirm: "Delete this maintenance schedule?",
        testEmail: "Send Test Email",
        testingEmail: "Sending Test Email...",
        submitting: "Saving...",
        empty: "No maintenance schedules yet.",
        enabled: "Enabled",
        disabled: "Disabled",
        emailMissing: "No email configured",
        loadError: "Unable to load maintenance data.",
        testEmailSuccess: "Test email sent successfully.",
        placeholderTarget: "e.g. CRAC Unit A",
        placeholderTask: "e.g. Filter replacement",
        placeholderTime: "08:00",
        placeholderNotes: "Optional work order or preparation notes",
        invalidTime: "Please enter time in 24-hour format (HH:MM).",
        selectCategory: "-- Select equipment --",
        selectTask: "-- Select task --",
        customInput: "Custom input...",
      }
    : {
        title: "維護排程",
        subtitle: "AI 智慧預防性維護與工單管理",
        createTitle: "新增維護排程",
        editTitle: "編輯維護排程",
        target: "維護對象",
        targetCategory: "設備類別",
        task: "維修項目",
        schedule: "排程時間",
        scheduleDate: "日期",
        scheduleTime: "時間",
        notifyBefore: "通知週期",
        notifyBeforeHint: "選擇提前通知時間，以利備料與人員安排",
        notifyBeforeSameDay: "當天",
        notifyBeforeOneDay: "一天前",
        notifyBeforeOneWeek: "一週前",
        notifyBeforeOneMonth: "一個月前",
        maintenanceCycle: "維修週期",
        maintenanceCycleHint: "自動循環排程，避免重複手動填寫",
        customDaysLabel: "自訂天數",
        assigned: "維護負責人",
        notify: "Email 提醒",
        notes: "備註",
        submit: "新增排程",
        update: "儲存修改",
        edit: "編輯",
        delete: "刪除",
        cancelEdit: "取消編輯",
        sentAt: "已發信時間",
        notSent: "尚未發信",
        deleteConfirm: "確定要刪除此維護排程嗎？",
        testEmail: "測試 Email",
        testingEmail: "測試寄送中...",
        submitting: "儲存中...",
        empty: "目前尚無維護排程。",
        enabled: "已啟用",
        disabled: "未啟用",
        emailMissing: "此帳號尚未設定 email",
        loadError: "無法載入維護資料。",
        testEmailSuccess: "測試 Email 已成功送出。",
        placeholderTarget: "例如：CRAC Unit A",
        placeholderTask: "例如：濾網更換",
        placeholderTime: "08:00",
        placeholderNotes: "可填寫工單內容、停機窗口或準備事項",
        invalidTime: "請輸入 24 小時制時間，格式為 HH:MM。",
        selectCategory: "-- 選擇設備類別 --",
        selectTask: "-- 選擇維修項目 --",
        customInput: "自行輸入...",
      };
}
