"use client";

import type { AppLanguage } from "@/shared/i18n/language";
import type { MaintenanceCopy } from "./types";

export function getMaintenanceCopy(language: AppLanguage): MaintenanceCopy {
  return language === "en"
    ? {
        title: "MAINTENANCE SCHEDULE",
        subtitle: "Preventative Maintenance & Work Orders",
        createTitle: "Create Schedule",
        editTitle: "Edit Schedule",
        target: "Target Equipment",
        task: "Task",
        schedule: "Schedule",
        scheduleDate: "Date",
        scheduleTime: "Time (24h)",
        recurrence: "Cycle Days",
        recurrenceHint: "Use 0 for one-time only; after each email send, the next send time moves forward by this many days.",
        assigned: "Assignee",
        notify: "Email Reminder",
        notes: "Notes",
        submit: "Create Schedule",
        update: "Save Changes",
        edit: "Edit",
        delete: "Delete",
        cancelEdit: "Cancel Edit",
        sentAt: "Sent At",
        notSent: "Not sent yet",
        deleteConfirm: "Delete this maintenance schedule?",
        testEmail: "Send Test Email",
        testingEmail: "Sending Test Email...",
        submitting: "Saving...",
        empty: "No maintenance schedules yet.",
        enabled: "Enabled",
        disabled: "Disabled",
        emailMissing: "No email configured",
        loadError: "Unable to load maintenance data.",
        testEmailSuccess: "Test email sent successfully.",
        placeholderTarget: "e.g. CRAC Unit A",
        placeholderTask: "e.g. Filter replacement",
        placeholderTime: "e.g. 14:30",
        placeholderRecurrenceDays: "e.g. 30",
        placeholderNotes: "Optional work order or preparation notes",
        invalidTime: "Please enter time in 24-hour format (HH:MM).",
        invalidRecurrenceDays: "Please enter cycle days as a non-negative integer.",
        recurrenceOneTime: "One-time",
      }
    : {
        title: "維護排程",
        subtitle: "預防性維護與工單",
        createTitle: "新增維護排程",
        editTitle: "編輯維護排程",
        target: "維護對象",
        task: "項目",
        schedule: "排程",
        scheduleDate: "日期",
        scheduleTime: "時間（24小時制）",
        recurrence: "週期天數",
        recurrenceHint: "輸入 0 代表單次；每次發信成功後，系統會把下一次發送時間往後加上這個天數。",
        assigned: "維護負責人",
        notify: "Email 提醒",
        notes: "備註",
        submit: "新增排程",
        update: "儲存修改",
        edit: "編輯",
        delete: "刪除",
        cancelEdit: "取消編輯",
        sentAt: "已發信時間",
        notSent: "尚未發信",
        deleteConfirm: "確定要刪除此維護排程嗎？",
        testEmail: "測試 Email",
        testingEmail: "測試寄送中...",
        submitting: "儲存中...",
        empty: "目前尚無維護排程。",
        enabled: "已啟用",
        disabled: "未啟用",
        emailMissing: "此帳號尚未設定 email",
        loadError: "無法載入維護資料。",
        testEmailSuccess: "測試 Email 已成功送出。",
        placeholderTarget: "例如：CRAC Unit A",
        placeholderTask: "例如：濾網更換",
        placeholderTime: "例如：14:30",
        placeholderRecurrenceDays: "例如：30",
        placeholderNotes: "可填寫工單內容、停機窗口或準備事項",
        invalidTime: "請輸入 24 小時制時間，格式為 HH:MM。",
        invalidRecurrenceDays: "請輸入大於或等於 0 的整數天數。",
        recurrenceOneTime: "單次",
      };
}
